# Site settings
title: New-PowerShellBlog
description: 'New home for eosfor.wordpress.com'
url: 'http://eosfor.github.io'
baseurl: ''
google_analytics: 'UA-111426314-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Andrey Vernigora'
  email: yet.another.powershell.guy@gmail.com

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: none

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate','jekyll-gist', 'jekyll-sitemap']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
