# Site settings
title: New-PowerShellBlog
description: 'New home for https://eosfor.wordpress.com'
url: 'http://eosfor.github.io'
baseurl: '/'
google_analytics: 'UA-111426314-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Andrey Vernigora'
  email: yet.another.powershell.guy@gmail.com

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
# highlighter: rouge
# highlighter: coderay

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: true
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    disable: false
    span:
      line_numbers: true
    block:
      line_numbers: true
      start_line: 1

plugins: [jekyll-gist]

gems: ['jekyll-paginate', 'jemoji', 'jekyll-sitemap', 'jekyll-gist']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
